version: '3.7'

services:
  client:
    container_name: cliff-client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/opt/app'
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
