version: '3.7'

services:
  postgres:
    container_name: cliff-postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: cliff
    volumes:
      - ./volumes/postgres:/data/postgres
    ports:
      - '5433:5432'
  redis:
    image: redis
    container_name: cliff-redis-container
    ports:
      - '6380:6379'
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    volumes:
      - ./volumes/redis:/data
  client:
    container_name: cliff-client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/opt/client'
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  server:
    container_name: cliff-server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/opt/server'
    ports:
      - 3333:3333
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
    depends_on:
      - redis
      - postgres
