version: '3.7'

services:
  postgres:
    container_name: cliff-postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: cliff
    volumes:
      - ./volumes/postgres:/data/postgres
    ports:
      - '5433:5432'
  redis:
    image: redis
    container_name: cliff-redis-container
    ports:
      - '6380:6379'
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    volumes:
      - ./volumes/redis:/data
  client:
    container_name: cliff-client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/opt/app
      - /opt/app/node_modules
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SERVER_HOST=${SERVER_HOST}
    stdin_open: true
    tty: true
  server:
    container_name: cliff-server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - ./server:/opt/app
      - /opt/app/node_modules
    ports:
      - 3333:3333
    depends_on:
      - redis
      - postgres
    environment:
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - PGUSER=${PGUSER}
      - PGHOST=${PGHOST}
      - PGPASSWORD=${PGPASSWORD}
      - PGDATABASE=${PGDATABASE}
      - PGPORT=${PGPORT}
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - APP_PORT=${APP_PORT}
      - SERVER_HOST=${SERVER_HOST}
