version: '3.3'

services:
  postgres:
    container_name: cliff-postgres-container
    image: postgres
    environment:
      POSTGRES_USER: ${PGUSER}
      POSTGRES_PASSWORD: ${PGPASSWORD}
      PGDATA: /data/postgres
      POSTGRES_DB: cliff
    volumes:
      - ./volumes/postgres:/data/postgres
    ports:
      - '5433:5432'
  redis:
    image: redis
    container_name: cliff-redis-container
    ports:
      - '6380:6379'
    command: 'redis-server --requirepass ${REDIS_PASSWORD} --appendonly yes'
    volumes:
      - ./volumes/redis:/data
  client:
    container_name: cliff-client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - ./client:/opt/app
    ports:
      - 7000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
      - REACT_APP_SERVER_URL=${SERVER_URL}
    stdin_open: true
    tty: true
  server:
    container_name: cliff-server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - '7001:8080'
      - '5005:5005'
    depends_on:
      - redis
      - postgres
    environment:
      - REDIS_HOST=${REDIS_HOST}
      - REDIS_PORT=${REDIS_PORT}
      - REDIS_PASSWORD=${REDIS_PASSWORD}
      - DS_URL=${PGURL}
      - DS_USER=${PGUSER}
      - DS_PASSWORD=${PGPASSWORD}
      - CLIENT_URL=${CLIENT_URL}
      - JAVA_TOOL_OPTIONS=-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=*:5005
