version: '3.7'

services:
  client:
    container_name: cliff-client-container
    build:
      context: ./client
      dockerfile: Dockerfile
    volumes:
      - './client:/opt/client'
    ports:
      - 5000:3000
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
  server:
    container_name: cliff-server-container
    build:
      context: ./server
      dockerfile: Dockerfile
    volumes:
      - './server:/opt/server'
    ports:
      - 3333:3333
    environment:
      - CHOKIDAR_USEPOLLING=true
    stdin_open: true
    tty: true
